# wrangler.toml
name = "passhashgen"                 # match the service name in the logs
main = "worker.js"
compatibility_date = "2025-10-24"

[[kv_namespaces]]
binding = "HASHES"
id = "uvu-md5-hashes"
preview_id = "uvu-md5-hashes"   # can be same as id if you pref
