name = "uvu-password-hash-demo"
main = "worker.js"
compatibility_date = "2025-10-24"

# If you’re using the KV version:
[[kv_namespaces]]
binding = "HASHES"
# Replace these two IDs after you create/bind the namespace:
id = "YOUR_PROD_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_NAMESPACE_ID"
